//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbsenceRecord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AbsenceRecord()
        {
            this.ExceptionCase = new HashSet<ExceptionCase>();
        }
    
        public System.Guid AbsenceRecordId { get; set; }
        public System.DateTime SpecDay { get; set; }
        public System.DateTime EndDay { get; set; }
        public int Id { get; set; }
        public byte Status { get; set; }
        public string Reason { get; set; }
        public string Remark { get; set; }
        public System.DateTime Checkintime { get; set; }
        public byte PeopleType { get; set; }
        public Nullable<System.Guid> StudentId { get; set; }
        public Nullable<System.Guid> TeacherId { get; set; }
        public System.Guid Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExceptionCase> ExceptionCase { get; set; }
        public virtual DataDictionary DataDictionary { get; set; }
        public virtual Student Student { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
