//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirRecord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AirRecord()
        {
            this.Attachment = new HashSet<Attachment>();
        }
    
        public System.Guid AirRecordId { get; set; }
        public int Id { get; set; }
        public byte Status { get; set; }
        public string Title { get; set; }
        public string Remark { get; set; }
        public System.DateTime Checkintime { get; set; }
        public System.DateTime EndTime { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.Guid RoomId { get; set; }
        public System.Guid TeacherId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attachment> Attachment { get; set; }
        public virtual Room Room { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
