//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arrangement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Arrangement()
        {
            this.ArrangementDetail = new HashSet<ArrangementDetail>();
            this.RoomPlan = new HashSet<RoomPlan>();
        }
    
        public System.Guid ArrangementId { get; set; }
        public int Id { get; set; }
        public byte Status { get; set; }
        public byte Type { get; set; }
        public string Title { get; set; }
        public int Frequence { get; set; }
        public int RoomNum { get; set; }
        public byte FrequenceType { get; set; }
        public string WeekDays { get; set; }
        public System.DateTime Checkintime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArrangementDetail> ArrangementDetail { get; set; }
        public virtual ArrangementAsset ArrangementAsset { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomPlan> RoomPlan { get; set; }
    }
}
