//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        public int Id { get; set; }
        public byte Status { get; set; }
        public byte Type { get; set; }
        public string Name { get; set; }
        public decimal Num { get; set; }
        public string Unit { get; set; }
        public string Remark { get; set; }
        public System.DateTime Checkintime { get; set; }
        public System.Guid SchoolId { get; set; }
    
        public virtual School School { get; set; }
    }
}
