//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HealthySchoolEntities : DbContext
    {
        public HealthySchoolEntities()
            : base("name=HealthySchoolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AbsenceRecord> AbsenceRecord { get; set; }
        public virtual DbSet<AirRecord> AirRecord { get; set; }
        public virtual DbSet<Arrangement> Arrangement { get; set; }
        public virtual DbSet<ArrangementAsset> ArrangementAsset { get; set; }
        public virtual DbSet<ArrangementDetail> ArrangementDetail { get; set; }
        public virtual DbSet<Attachment> Attachment { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<ClaimRecord> ClaimRecord { get; set; }
        public virtual DbSet<County> County { get; set; }
        public virtual DbSet<DataDictionary> DataDictionary { get; set; }
        public virtual DbSet<DisinfectRecord> DisinfectRecord { get; set; }
        public virtual DbSet<Document> Document { get; set; }
        public virtual DbSet<EnterRecord> EnterRecord { get; set; }
        public virtual DbSet<ExceptionCase> ExceptionCase { get; set; }
        public virtual DbSet<ExceptionCaseHistory> ExceptionCaseHistory { get; set; }
        public virtual DbSet<Holiday> Holiday { get; set; }
        public virtual DbSet<Mng_UserRole> Mng_UserRole { get; set; }
        public virtual DbSet<Module> Module { get; set; }
        public virtual DbSet<ModuleItem> ModuleItem { get; set; }
        public virtual DbSet<ModuleItemPrivilege> ModuleItemPrivilege { get; set; }
        public virtual DbSet<ModuleRolePermission> ModuleRolePermission { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<NewsAttachment> NewsAttachment { get; set; }
        public virtual DbSet<Notification> Notification { get; set; }
        public virtual DbSet<Parent> Parent { get; set; }
        public virtual DbSet<ParentCheckin> ParentCheckin { get; set; }
        public virtual DbSet<Privilege> Privilege { get; set; }
        public virtual DbSet<Province> Province { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<RolePermission> RolePermission { get; set; }
        public virtual DbSet<Room> Room { get; set; }
        public virtual DbSet<RoomPlan> RoomPlan { get; set; }
        public virtual DbSet<RoomTeacher> RoomTeacher { get; set; }
        public virtual DbSet<School> School { get; set; }
        public virtual DbSet<StockIn> StockIn { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<StudentBbtRecord> StudentBbtRecord { get; set; }
        public virtual DbSet<StudentParent> StudentParent { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
        public virtual DbSet<TeacherBbtRecord> TeacherBbtRecord { get; set; }
        public virtual DbSet<TeacherLog> TeacherLog { get; set; }
        public virtual DbSet<TeacherRole> TeacherRole { get; set; }
        public virtual DbSet<TeacherTag> TeacherTag { get; set; }
        public virtual DbSet<TeamClassroom> TeamClassroom { get; set; }
        public virtual DbSet<TeamNews> TeamNews { get; set; }
        public virtual DbSet<TeamSchedule> TeamSchedule { get; set; }
        public virtual DbSet<TeamStudent> TeamStudent { get; set; }
        public virtual DbSet<TeamTeacher> TeamTeacher { get; set; }
        public virtual DbSet<Tips> Tips { get; set; }
        public virtual DbSet<VerifyCode> VerifyCode { get; set; }
        public virtual DbSet<Visitor> Visitor { get; set; }
        public virtual DbSet<WeiXinUser> WeiXinUser { get; set; }
        public virtual DbSet<Asset> Asset { get; set; }
        public virtual DbSet<TinyAppSession> TinyAppSession { get; set; }
        public virtual DbSet<Team> Team { get; set; }
        public virtual DbSet<Schedule> Schedule { get; set; }
    }
}
