//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public System.Guid DocumentId { get; set; }
        public int Id { get; set; }
        public byte Status { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> PublishTime { get; set; }
        public string Url { get; set; }
        public string Ext { get; set; }
        public int FileSize { get; set; }
        public Nullable<int> Views { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
        public System.DateTime Checkintime { get; set; }
        public System.Guid TeacherId { get; set; }
    
        public virtual Teacher Teacher { get; set; }
    }
}
