//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnterRecord
    {
        public System.Guid EnterRecordId { get; set; }
        public int Id { get; set; }
        public byte Status { get; set; }
        public System.DateTime Checkintime { get; set; }
        public decimal Temperature { get; set; }
        public byte ColorStatus { get; set; }
        public byte PeopleType { get; set; }
        public Nullable<System.Guid> TeacherId { get; set; }
        public Nullable<System.Guid> StudentId { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
