//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExceptionCase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExceptionCase()
        {
            this.Notification = new HashSet<Notification>();
            this.ExceptionCaseHistory = new HashSet<ExceptionCaseHistory>();
        }
    
        public System.Guid ExceptionCaseId { get; set; }
        public byte Type { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public byte PeopleType { get; set; }
        public int Id { get; set; }
        public byte Status { get; set; }
        public System.DateTime Checkintime { get; set; }
        public string Remark { get; set; }
        public Nullable<System.Guid> AbsenceRecordId { get; set; }
        public Nullable<System.Guid> TeacherId { get; set; }
        public Nullable<System.Guid> StudentId { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public Nullable<System.Guid> StudentBbtRecordId { get; set; }
        public Nullable<System.Guid> TeacherBbtRecordId { get; set; }
        public Nullable<System.Guid> ParentCheckinId { get; set; }
    
        public virtual AbsenceRecord AbsenceRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExceptionCaseHistory> ExceptionCaseHistory { get; set; }
        public virtual Parent Parent { get; set; }
        public virtual ParentCheckin ParentCheckin { get; set; }
        public virtual Student Student { get; set; }
        public virtual StudentBbtRecord StudentBbtRecord { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual TeacherBbtRecord TeacherBbtRecord { get; set; }
    }
}
