//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleItemPrivilege
    {
        public System.Guid ModuleItemId { get; set; }
        public System.Guid PrivilegeId { get; set; }
        public int Id { get; set; }
    
        public virtual ModuleItem ModuleItem { get; set; }
        public virtual Privilege Privilege { get; set; }
    }
}
