//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Module()
        {
            this.ModuleItem = new HashSet<ModuleItem>();
            this.ModuleRolePermission = new HashSet<ModuleRolePermission>();
        }
    
        public System.Guid ModuleId { get; set; }
        public int Id { get; set; }
        public string Name { get; set; }
        public string Comment { get; set; }
        public bool IsShow { get; set; }
        public int OrderFlag { get; set; }
        public int Num { get; set; }
        public string Picture { get; set; }
        public string PageUrl { get; set; }
        public byte Status { get; set; }
        public System.DateTime CheckinTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModuleItem> ModuleItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModuleRolePermission> ModuleRolePermission { get; set; }
    }
}
