//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ModuleItem()
        {
            this.RolePermission = new HashSet<RolePermission>();
            this.ModuleItemPrivilege = new HashSet<ModuleItemPrivilege>();
            this.ModuleItem1 = new HashSet<ModuleItem>();
        }
    
        public System.Guid ModuleItemId { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public int Id { get; set; }
        public string Name { get; set; }
        public string PageUrl { get; set; }
        public string MenuItemPicture { get; set; }
        public bool IsMenuItem { get; set; }
        public System.Guid ModuleId { get; set; }
        public int OrderFlag { get; set; }
        public byte Status { get; set; }
    
        public virtual Module Module { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RolePermission> RolePermission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModuleItemPrivilege> ModuleItemPrivilege { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModuleItem> ModuleItem1 { get; set; }
        public virtual ModuleItem ModuleItem2 { get; set; }
    }
}
