//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParentCheckin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParentCheckin()
        {
            this.ExceptionCase = new HashSet<ExceptionCase>();
        }
    
        public System.Guid ParentCheckinId { get; set; }
        public int Id { get; set; }
        public byte Status { get; set; }
        public System.DateTime Checkintime { get; set; }
        public byte ColorStatus { get; set; }
        public System.Guid ParentId { get; set; }
        public System.DateTime SpecDay { get; set; }
        public string PhotoUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExceptionCase> ExceptionCase { get; set; }
        public virtual Parent Parent { get; set; }
    }
}
