//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.AbsenceRecord = new HashSet<AbsenceRecord>();
            this.EnterRecord = new HashSet<EnterRecord>();
            this.ExceptionCase = new HashSet<ExceptionCase>();
            this.Tips = new HashSet<Tips>();
            this.StudentParent = new HashSet<StudentParent>();
            this.StudentBbtRecord = new HashSet<StudentBbtRecord>();
            this.TeamStudent = new HashSet<TeamStudent>();
        }
    
        public System.Guid StudentId { get; set; }
        public string AvatarUrl { get; set; }
        public string Name { get; set; }
        public int Id { get; set; }
        public byte Status { get; set; }
        public byte HealthyStatus { get; set; }
        public string IdNo { get; set; }
        public int No { get; set; }
        public byte ColorStatus { get; set; }
        public System.DateTime Checkintime { get; set; }
        public System.Guid TeamId { get; set; }
        public Nullable<System.DateTime> LastAccessTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AbsenceRecord> AbsenceRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnterRecord> EnterRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExceptionCase> ExceptionCase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tips> Tips { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentParent> StudentParent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentBbtRecord> StudentBbtRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamStudent> TeamStudent { get; set; }
        public virtual Team Team { get; set; }
    }
}
