//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherBbtRecord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TeacherBbtRecord()
        {
            this.ExceptionCase = new HashSet<ExceptionCase>();
        }
    
        public System.Guid TeacherBbtRecordId { get; set; }
        public Nullable<System.DateTime> SpecDay { get; set; }
        public int Id { get; set; }
        public byte Status { get; set; }
        public System.DateTime Checkintime { get; set; }
        public decimal Temperature { get; set; }
        public System.Guid TeacherId { get; set; }
        public System.Guid Measurer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExceptionCase> ExceptionCase { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual Teacher Teacher1 { get; set; }
    }
}
