//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Team()
        {
            this.Student = new HashSet<Student>();
            this.TeamNews = new HashSet<TeamNews>();
            this.TeamSchedule = new HashSet<TeamSchedule>();
            this.TeamClassroom = new HashSet<TeamClassroom>();
            this.TeamTeacher = new HashSet<TeamTeacher>();
            this.TeamStudent = new HashSet<TeamStudent>();
        }
    
        public System.Guid TeamId { get; set; }
        public int Id { get; set; }
        public string Name { get; set; }
        public string NickName { get; set; }
        public byte Status { get; set; }
        public int Grade { get; set; }
        public int OrderNo { get; set; }
        public byte ColorStatus { get; set; }
        public System.DateTime Checkintime { get; set; }
        public int StudentNum { get; set; }
        public int TeacherNum { get; set; }
        public int ParentNum { get; set; }
        public Nullable<System.Guid> RoomId { get; set; }
        public System.Guid SchoolId { get; set; }
        public int GradeYear { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual School School { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamNews> TeamNews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamSchedule> TeamSchedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamClassroom> TeamClassroom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamTeacher> TeamTeacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamStudent> TeamStudent { get; set; }
    }
}
