//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tips
    {
        public System.Guid TipsId { get; set; }
        public int Id { get; set; }
        public byte Status { get; set; }
        public byte Type { get; set; }
        public string Content { get; set; }
        public string FontColor { get; set; }
        public System.DateTime ActionTime { get; set; }
        public System.DateTime Checkintime { get; set; }
        public Nullable<System.Guid> RoomId { get; set; }
        public Nullable<System.Guid> StudentId { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual Student Student { get; set; }
    }
}
