//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class VerifyCode
    {
        public System.Guid VerifyCodeId { get; set; }
        public int Id { get; set; }
        public byte Status { get; set; }
        public System.DateTime Checkintime { get; set; }
        public string Mobile { get; set; }
        public string Code { get; set; }
        public string Ip { get; set; }
        public Nullable<System.DateTime> VerifyTime { get; set; }
        public string UnionId { get; set; }
    
        public virtual WeiXinUser WeiXinUser { get; set; }
    }
}
